credentials:
  usernames:
    admin:
      name: admin
      password:  'placeholder'
    fin.analyst:
      name: Financial Statement Analyst
      password:  'placeholder' 
    h.khandani:
      name: Hossein Khandani
      password:  'placeholder'

cookie:
  expiry_days: 1
  key: 'random_secret_key_123'
  name: 'financial_analyzer_cookie'


